version: '3.7'

services:
## DJANGO APP
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ptt_backend
    container_name: ptt_backend
    entrypoint: /ptt_backend/entrypoint.sh
    # stdin_open: true
    # tty: true
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    networks:
      - servicenetwork

## POSTGRESQL
  db:
    image: postgres
    container_name: ptt_db
    restart: always
    volumes:
      - ./data/pgdata:/var/lib/postgresql/my_data
    env_file:
      - ./.env
    ports:
      - "5454:5432"
    networks:
      - servicenetwork

## REDIS
  redis:
    image: redis:alpine
    container_name: ptt_cache
    restart: always
    env_file:
      - ./.env
    ports:
      - "6389:6379"
    networks:
      - servicenetwork

networks:
    servicenetwork:
        driver: bridge
