# Generated by Django 4.1.2 on 2022-10-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_log", "0002_alter_timelog_start_time"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="timelog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("end_time__isnull", True),
                    ("end_time__gte", models.F("start_time")),
                    _connector="OR",
                ),
                name="End time (when not null) must be grater than Start time",
            ),
        ),
    ]
