# Generated by Django 4.1.2 on 2022-10-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_log", "0004_alter_timelog_end_time_alter_timelog_start_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timelog",
            old_name="project_assignee",
            new_name="project_assignment",
        ),
    ]
