# Generated by Django 4.1.2 on 2022-10-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_log", "0005_rename_project_assignee_timelog_project_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelog",
            name="end_time",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
    ]
