# Generated by Django 4.1.2 on 2022-10-24 14:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectassignment",
            unique_together={("user", "project")},
        ),
    ]
